### ISSUE TITLE
Issue with Serenity and SauceLabs integration with JUnit

### ISSUE THREAD

**Issue by praty2goli** [michalsi/michalsi.github.io#1]
Hi @michalsi  ,

i tried using the code for Serenity and SauceLabs integration with JUnit however i can still see the name which is given in serenity.properties file. I'm using the @Rule in driver script class and it is extending saucelabWatcher class.can u explain where i'm making a mistake .

Regards,
Prateek

**Comment by michalsi** [comment]
Hey @praty2goli,
Thanks for reaching out. I'm sorry to hear that you've got troubles with instructions. Unfortunately it was really long time ago for me when I last time touched Serenity. I'm not able to quickly verify your particular issue since I'm involved in few other projects now.
Those notes are not meant to replace official docs. I hope you don't mind if I close that issue.
